#!/bin/bash

# Check if the script is being sourced
(return 0 2>/dev/null) || { 
    echo "This script should be sourced, not executed." 
    exit 1 
}

# Check if .profile already has .post_profile
if ! grep -q ".post_profile" "$HOME/.profile"; then
    # We want this to output $HOME without expansion
    # shellcheck disable=SC2016
    echo '. "$HOME/.post_profile"' >>"$HOME/.profile"
fi
